name: Sample Run Max 2 Jobs In Parallel
on: 
  push:
      branches:
        - '*'
jobs:
  detect-changed-lambdas:
    name: Detect changed Lambda functions
    runs-on: ubuntu-latest

    outputs:
      lambdas_files: ${{ steps.detect_changes.outputs.lambdas_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Detect changed Lambda files
        uses: dorny/paths-filter@v2
        id: detect_changes
        with:
          base: 'TECHM-01_test'
          list-files: 'json'
          filters: |
            lambdas: 'lambda/**'

            
  apply-changed-lambdas:
    name: Build Docker images for changed Lambdas
    needs: detect-changed-lambdas
    runs-on: ubuntu-latest

    strategy:
      matrix:
        filename: ${{ fromJson(needs.detect-changed-lambdas.outputs.lambdas_files) }}
      fail-fast: false
      
    steps:
    
    - name: Build Docker image and push to AWS ECR
      id: build_and_push
      env:
        ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: '${{ env.DOCKER_TAG }}'
        MATRIX_FILENAME: ${{ matrix.filename }}
        
      run: echo Run ${MATRIX_FILENAME}