name: Sample Matrix Parallel
on: 
on: 
  push:
      branches:
        - '*'
jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        run: ['run1', 'run2']
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
