name: Sample Run Include Syntax
on: 
  push:
      branches:
        - '*'
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        run: ['run1', 'run2']
        include:
          - run: 'run3'
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
    - run: sleep 5
    - run: date